SECRET_KEY = "somesupersecretkeythatnoonewilleverguess"

AWS_ACCESS_KEY_ID='AKIAJE64AT6LN7EW34WQ'
AWS_SECRET_ACCESS_KEY='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'
FLASKS3_BUCKET_NAME = 'codemd-static'
FLASKS3_REGION = 'USEAST'
